name: CI-CD
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # runs weekly on Sunday at 01:00 UTC
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build -o ./_site
      - uses: actions/upload-pages-artifact@main
  cd:
    needs: ci
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: false
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@main
