name: Publish
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0' # runs weekly on Sunday at 01:00 UTC
  pull_request:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build .#site-github -j 4
      - uses: peaceiris/actions-gh-pages@main
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result
